server:
  port: 8080

template:
  templates:
    - { "templateId": "1","templateFilePath": "/Users/weikunkun/IdeaProjects/kafka-study/src/main/resources/template/template.json","active": true }
    - { "templateId": "2","templateFilePath": "/Users/weikunkun/IdeaProjects/kafka-study/src/main/resources/template/template.json","active": false }
  template-result-type: 0  # 0-文件获取 1-数据库获取 2-ES
  template-result-file-path: "/Users/weikunkun/IdeaProjects/kafka-study/src/main/resources/template/templateResult.json"

wechat:
  kafka:
    bootstrap_servers: "47.95.196.129:9092"
    acks_config: "all"
    partitioner_class: "com.wkk.kafka.producer.PartitionSample"


logging:
  config: classpath:logback.xml
